### PR TITLE
Update language 'de'

### PR DESCRIPTION
**Pull request by Rouby**

### CODE REVIEW

**Comment by mlenser** [comment]
Many words are purposefully not capitalized to provide a normal sentence structure. For example "Initiative Bonus" should read "Initiative bonus". Proper nouns for example the names of a class feature would break this mold. Could you fix that?

Also I added all the class features to the translations and it would be awesome to translate those at some point.

**Comment by Rouby** [comment]
In german words (pronouns) are capitalized even midsentence, so it would look more natural for a native speaker if those nouns are capitalized.

I will tackle class features some time in the near future ;) Would you mind adding new keys to the other translation files too in the future? Maybe with an empty translation or "TRANSLATION_NEEDED"? Would be easier for me to find new items then.

**Comment by mlenser** [comment]
But a word like "bonus" isn't a pronoun: "A pronoun (I, me, he, she, herself, you, it, that, they, each, few, many, who, whoever, whose, someone, everybody, etc.) is a word that takes the place of a noun. In the sentence Joe saw Jill, and he waved at her, the pronouns he and her take the place of Joe and Jill, respectively."
Some examples: "Check-Bonus"(Bonus), "Verstecke NPC Info"(Info), "Verstecke Rettungswurf Fehlschlag". Those seem incorrect based on English and my limited understanding of Germanic Languages. Obviously you're the native speaker and I don't want to overrule you, I just want to verify that this is correct.

I would have to change the way translations work a bit to give you new fields to fill out. Currently I fall back on English if the key isn't found. Instead I'd have to check for a certain keyword like "NEEDS TRANSLATION". It can be done though - I'll work on that.

**Comment by Rouby** [comment]
Sorry, I thought about noun (not pronoun) :fearful: 

But those examples you gave are correctly capitalized (if they were seen as normal "sentences").

**Comment by mlenser** [comment]
Your call~

**Pull request merged**
