### PR TITLE
Updated for 7.3.8

### PR DESCRIPTION
**Pull request by Netoen**
Gone through every line and merged it properly

### CODE REVIEW

**Comment by Netoen** [comment]
Also, as a side note, I've dealt with Skills not translating error. Now it's all nice.

**Comment by mlenser** [comment]
The indentation is incorrect so the diff isn't showing. I'll have to manually merge it.

**Comment by Netoen** [comment]
What tool do you use to merge ? I simply take your en.js and add lines from it to my previous translation, and I did indeed notice tabulation was off.

**Comment by mlenser** [comment]
Thanks!

**Pull request merged**
