### PR TITLE
french translation added

### PR DESCRIPTION
**Pull request by Alzam01**
I think that I have an old version of .../components/spells/spell-page.html, but I'm not sure where to find the new version.

### CODE REVIEW

**Comment by mlenser** [comment]
If you could update to the latest and get rid of the extra line ending changes that'd allow me to merge it right away.

Otherwise I'll have to do this later in the week.

**Comment by Alzam01** [comment]
I'm trying to get rid of the extra line, but it seem that github is adding them automatically when I click the "commit change" button 
fthtfh
In the preview, it show that there is no newline, but ther is one if I edit the file. I must be doing something wrong, can you help me ?

**Comment by mlenser** [comment]
The line endings are likely caused by your editor. I assume you're on Linux or Mac to produce those line endings. Some editors like intellij can change line endings.

If you can't figure it out then no big deal. Though the other changes are important. Taking the current code in that area would be easiest for me.

Otherwise I can do it all manually later in the week.

**Comment by Alzam01** [comment]
I'm using windows and I tried editing directly in github for the line problem.

For the current code, I'm a little lost : the code that is actually showed when I look in "file changed" is your Shaped v2, and it didn't have some of your latest edits (spell-page and old weapons unchecked by default for exemple). Should I compare with your latest version (branch : master) or with the one that github show me (branch : v2) ? In others words, when you go in "files changed" and check the part "components/spells/spell-page.html", is it the good code ? Because it's not the code that I see when I go in your repository... Is it because I did something wrong when I created the pull request ?

Sorry if i'm annoying you

**Comment by mlenser** [comment]
Ignore the v2 branch. That's a revamp that I'll work on over time.

Surprising that you have different line endings on Windows. Hmmm no idea then.

The main changes I'm talking about is the attributes I 're-added to the spell-page and the toggles on the weapons page. Minor, but I'll have to fix them if you don't.

You're not bothering, you're helping. Don't apologize. :)

**Comment by Alzam01** [comment]
Ok, the pull request should be good now.

**Comment by mlenser** [comment]
Ah! I forgot about this! I'll merge it now!

**Comment by mlenser** [comment]
Or not :(

**Comment by Alzam01** [comment]
Old on, it's comming back soon :)

**Pull request closed without merging**
