### PR TITLE
Innate casting fix

### PR DESCRIPTION
**Pull request by Orta15a**
Fixing the french phrase for Innate casting after seeing it didn't made sense

### CODE REVIEW

**Comment by mlenser** [comment]
Can you fix the last line? I typically fix it after merging, but it'd be easier to have you merge it in without that diff.

**Comment by Orta15a** [comment]
Done, it's my beautifier addon for Json that messes the last line. I'll take extra care with the next Pull requests.

**Comment by mlenser** [comment]
Still seems to be different according to github: https://github.com/mlenser/roll20-character-sheets/pull/176/files

**Comment by Orta15a** [comment]
There you go. I had to install and configure Github for windows, the web editor was always adding end of line character.

**Comment by mlenser** [comment]
thanks

**Pull request merged**
