### PR TITLE
Some updates to German translation

### PR DESCRIPTION
**Pull request by joesinghaus**
Still far from finished, but at least they are somewhat more comprehensive now.

### CODE REVIEW

**Comment by mlenser** [comment]
Hey @joesinghaus thanks for taking the time to do this.

However some aren't correct. "ARMOR_CLASS" for example is the full text while "AC" is the short (where RK already is). I also see you changed some of @Rouby 's translations.

Perhaps @Rouby can review?

**Comment by Rouby** [comment]
I had a quick look and seems all good to me :+1:

**Comment by joesinghaus** [comment]
The problem with e.g. armor class is that it grows out of the bounds of the field in the German version. One could introduce a line break instead, making it Rüstungs-<br>klasse, maybe that will fit. But Rüstungsklasse in full just looks awful. Problems like these occurred a number of times.

Apart from these stylistical issues, I think I only changed translations which were wrong (grammatically, or not translated in context). I'm glad you agree with the changes, Rouby (is there any place where you disagree with what I've changed?).

**Comment by mlenser** [comment]
Yup, German compound words.

If you're happy with it then I'll accept it.

**Comment by joesinghaus** [comment]
While not happy with the overall state, I'm confident enough that this is a marked improvement, feel free to accept.

**Pull request merged**
