### PR TITLE
Add missing stuff to JSON

### PR DESCRIPTION
**Pull request by Alzam01**
Add missing stuff :
- stuff from drop down menu
- stuff from placeholder (still missing some spell placeholder)

Add for better french translation : SPELL_SLOTS_TITLE / SPELL_POINTS_TITLE / WARLOCK_SPELL_SLOTS. Last one is not necessary, I'm good if you change the warlock spell slots title from {{'CLASSES.WARLOCK' | translate}} {{'SPELL_SLOTS' | translate}} to {{'SPELL_SLOTS' | translate}} ({{'CLASSES.WARLOCK' | translate}}) ---> "Spell slots (Warlock)" instead of "Warlock Spell slots".

I didn't update the other files to use the new stuff in the JSON yet.

### CODE REVIEW

**Comment by mlenser** [comment]
Things in selects cannot be pulled from translations so there is no need to add "ARMOR_TYPE", "SCHOOLS", "EXPERTISE", "FINESSE", "LONG_REST", "OTHER", "PROFICIENT", "SHORT_REST", "SPELLCASTING_FULL", "SPELLCASTING_HALF", "SPELLCASTING_THIRD", "UNARMORED", or "UNPROFICIENT".
Selects have to be manually translated in a few places.

Placeholders as well cannot be translated so that gets rid of "DAMAGE_TYPE", "HALF_DAMAGE", "IF_THE_TARGET_IS", "INSTANTANEOUS", "ONE_CREATURE", and "OR".

PC I assume is for the toggle at the top? That is in the HTML before the flags and therefore cannot be translated. I can try to fix that though.

"SPELL_POINTS_TITLE", "SPELL_SLOTS_TITLE", and "WARLOCK_SPELL_SLOTS" are fine.

**Comment by Alzam01** [comment]
Oh, I assumed it was possible to translate that :(.

**Comment by mlenser** [comment]
Well we can still do the other parts like "PC", "SPELL_POINTS_TITLE", "SPELL_SLOTS_TITLE", and "WARLOCK_SPELL_SLOTS".

Indeed it sucks that selects and placeholders can't be translated.

**Comment by Alzam01** [comment]
Yep, I'm gonna open a new pull request.
Maybe I can list where the selects/placeholders are, so other translators will not have to search for them ?

**Pull request closed without merging**
