### PR TITLE
Suggested approach to exposing row_id

### PR DESCRIPTION
**Pull request by symposion**
For use with things like the ammo update in the companion script
- otherwise there's no unique way to identify the row that generated
  a particular roll output.

I don't know if there's a better way of doing this - is there a built-in syntax for getting hold of the repeating section id in a roll query? It's not documented anywhere I can see, and so far no one on the forums has given me any helpful suggestions.

The alternative would be to key it off the name of the attack, but there's obviously no guarantee that that will be unique (daft though it would be for someone to make several attacks with the same name)

### CODE REVIEW

**Comment by mlenser** [comment]
Users can use the dev tools to find an id. We should not store the id for everything and then display it in the roll template - it's technical information.

**Comment by symposion** [comment]
It's not really for users (which is why I've hidden it from the roll template output) - it's to provide a way for scripts to be able to tie a roll template output back to a particular attack on the sheet. I can't see another way of reimplementing the old ammo update functionality reliably. When you had "fake" repeating sections on the old sheet, you put a row index into the roll template output as part of your build process, but there's no way to duplicate that no you're using real repeating sections. Do you see what I'm getting at?

**Comment by mlenser** [comment]
According to Aaron ammo works with the current implementation: https://app.roll20.net/forum/post/3004452/5e-shaped-v2-dot-1-3-npcs/?pageforid=3031907#post-3031907

You could use his command in freeform (I believe that will call it - I forget exactly if that works)

**Comment by symposion** [comment]
Ah, ok. That would be something of a regression vs the old scripts then. Before you could just turn it on and it would work automatically. Now you're going to have to open up the browser dev tools and manually put an ammo command into every attack on every character by hand. If we put the attack_id as a hidden field into the roll template, this could "just work" for anyone who had the script installed and turned on automatic ammo updating. Do you really feel that the inclusion of this hidden field is so bad that it justifies that loss of functionality?

**Comment by mlenser** [comment]
I don't know enough on the topic to give an answer. I'm just referencing the knowledge that I do know.

I do think storing an id is bad - I'd then have to store the id of every repeating section item.

**Comment by symposion** [comment]
Well, I'm with you on storing the id, I don't like it either. Unfortunately I don't see another way to re-implement the old script's automatic ammo functionality unless there's a way for the roll expression to access the id directly, without it having to be copied into an attribute.

There's no particular reason why this _has_ to apply to every repeating section. It's only necessary if there's a compelling case for providing a means for the API to respond to the chat output that the section generates.  I guess any section of the sheet that has uses/charges is possibly a candidate, since the API can add value by handling this stuff automatically for people; but in most of these cases the utility is marginal because they're less frequently used and it's not that much of an ask to manually decrement the uses remaining. Ammo, on the other hand, gets used a _lot_, and the ranged attacks are often used without the sheet open. 

Would it make you more comfortable with it if we had something like this:
- Checkbox for auto_ammo on ranged weapons
- Hidden field for ammo_field_name
- Hidden field is populated by sheet worker when the checkbox is ticked
- Hidden field is output as part of the attack roll
- Script can now directly lookup the relevant ammo field and decrement it if this functionality is enabled

It achieves the same thing, but it is more focussed on the specific use case and it doesn't set a precedent of including the row id on every repeating section?

**Comment by mlenser** [comment]
This is going to be a problem for every sheet that uses repeating. I wouldn't expect every sheet to handle this. I'll talk to Aaron to see if he has ideas for how to solve this on the script end (which needs to be updated to work w/ repeating).

My goal here would be to do it correctly, not just an option that works. If that avenue fails then we can consider hacks like this.

**Comment by symposion** [comment]
Great! I'm completely in agreement with you on that one - I'd much rather it wasn't hacky as well. 

One possible alternative would be to turn the thing on it's head. You could tell the script to generate the freeform sections for all attacks with an auto_ammo toggle selected for all selected tokens. Personally I don't like it as much, but it would certainly take some of the pain out of it for the user.

Having said that, I do think it's worth considering the wider question of how you can design the sheet for API extensibility. When we build dynamic HTML pages, we start with a good base of semantic markup with little or no direct reference to the JS embedded within it, and then apply the JS afterwards to add extended behaviours for user agents that support it. That keeps the markup and the JS loosely coupled.

In the same way, it strikes me as more elegant to have character sheets that output the core information as "semantic markup" in the form of roll template fields (with the roll template itself acting as the CSS, effectively), and then have scripts (if present) selectively process the information that is output to provide extended behaviours. The alternative is to fill up the semantic space of the character attributes with api calls shoe-horned into freeform text fields, which seems much "hackier" to me than including a hidden row id in the output. When you start to think of the roll output as not just a display format, but also a messaging interface to any API scripts that might want to act on the information, I think the inclusion of what is essentially a primary key onto a relevant data table, seems a lot more reasonable.

Final thought: if that still seems unpleasant to you, perhaps the long term solution is to build a proper API eventing interface into the sheet, independent of the roll outputs. It would be a lot more work, but if every output from the sheet _also_ generated an API call that any script could choose to hook into, complete with all of the internal information that might be relevant, that would solve all of these problems quite neatly and provide a very robust framework for future extension.

**Comment by mlenser** [comment]
So I'd suggest we chill on this for a week or two as roll20 may implement a pseudo field (I heard it mentioned).

Does that work for you?

**Comment by symposion** [comment]
Yep that works for me... the same little bird came and sang in my ear too ;-)

**Comment by symposion** [comment]
Dumping this as irrelevant for the time being.

**Pull request closed without merging**
