### PR TITLE
updated for 7.7.4 and translated all ClassFeatures

### PR DESCRIPTION
**Pull request by Netoen**
Yey ! Btw, in Features and Traits, in field Recharge Short/Long rest doesn't get translated.

### CODE REVIEW

**Review by mlenser — CHANGES_REQUESTED** [review]
768 additions and 748 deletions :(

I believe the issue is your version has a space after the colons. Roll20 set this format so I can't change it, unfortunately. Since this PR will likely be a regular occurrence can you change the code style to match so the diff is manageable? Thanks.

**Comment by Netoen** [comment]
Sure thing, I'll look into it right now.

**Comment by mlenser** [comment]
Created https://bitbucket.org/mlenser/5eshaped/issues/40/traits-short-long-rest-not-translated to handle short/long rest translations

**Comment by Netoen** [comment]
Do I need anything else ? Like delete #173 and create a new one ?

**Review by mlenser — APPROVED** [review]

**Review by mlenser — APPROVED** [review]

**Comment by mlenser** [comment]
I can't seem to merge this. Can you open a new one?

**Pull request closed without merging**
