### PR TITLE
Use gulp-inject to create multiple melee and ranged weapon blocks from templates

### PR DESCRIPTION
**Pull request by jjsheets**
Don't forget to npm install gulp-inject (and possibly npm install --save-dev gulp-inject) to make the gulp continue to work. I pulled out the first block of melee and ranged weapons into their own files in the components directory, modified weapons.html and gulpfile.js to automatically duplicate numbered versions of the templates into the final result. I used {{num}} in place of the section number (0 to 6) in the template, and used a simple loop in the gulpfile to duplicate the templates.

### CODE REVIEW

**Comment by mlenser** [comment]
There is no line break at the end of the loop. Any idea how to fix that?

**Comment by jjsheets** [comment]
Possibly change the `return s;` to `return s + "\n";` on lines 18 and 29 of gulpfile.js?

Though I have compiled the changes into my custom version and they work quite well as is.

**Comment by mlenser** [comment]
You have the line breaks in the html files which doesn't work on my machine for some reason. Putting it in the include is better as it won't happen on the last one.

In the loop of the gulp file I added this this:

if(i !== numberOfWeapons - 1) {
    s += '\n\n';
}

numberOfWweapons is defined as 7;

**Comment by jjsheets** [comment]
Sounds good. I think similar template techniques could be used in other spots if you wanted to break things down even more, but it might only be useful on the more complex stuff like class actions.

**Comment by mlenser** [comment]
I'll implement it for actions, class actions, spells, and any others as well.

**Comment by jjsheets** [comment]
Anything that is a Roll20 Repeating action in a fieldset tag doesn't need this I think, though it may be useful to create the different spell level sections which would have the repeating sections roll20 uses inside them. That said, one thing I hate about roll20's repeating sections is that they cannot easily support custom macro text per action/spell at this point, which would be excellent for using API scripts for tracking ammunition, spell uses, action uses, token mods, etc. If you run into any issues and need an extra pair of eyes to look at things, let me know.

**Pull request merged**
