### PR TITLE
translation of spellbook

### PR DESCRIPTION
**Pull request by Rouby**

### CODE REVIEW

**Comment by Rouby** [comment]
I have merged my branch with the things you did (i just accepted all your changes and overwrote mine)

**Comment by mlenser** [comment]
Are you sure you forked the right version? I see a lot of things that I changed over the last ~2 weeks that roll20 has not updated yet.

For example I removed cantrips for Paladin and Ranger, but I see them in your commits.

Also, make sure your tabbing is correct. For example tr should be tabbed in from thead and tbody.

**Comment by Rouby** [comment]
Hm actually that might be true. Those things should be contained to the spellbook tab tho.

The translations are from one of my players who send them to me a couple of hours ago. I think he worked off of the old version.

**Comment by mlenser** [comment]
There are thousands of changes all over, not just the spellbook.

**Comment by Rouby** [comment]
Are you sure? I only see changes in spellbook-section.

**Comment by mlenser** [comment]
I'll manually merge the changes, but for future things you guys should be on the latest code and update every day.

**Comment by Rouby** [comment]
Ok, thanks for your efforts again. I will forward that.

**Comment by mlenser** [comment]
Done. Please don't make me do this again. :(

I'm currently splitting the pages and will compile it all via Gulp so if you're working on other pages please wait until I finish that (likely today).

**Comment by Rouby** [comment]
Yep that sounds like a good plan.

**Comment by mlenser** [comment]
I've committed the split if you want to work on other pages.

Thanks again for your contributions.

**Pull request closed without merging**
