### PR TITLE
translations

### PR DESCRIPTION
**Pull request by Rouby**
First core page (most longer texts are still stubs)

### CODE REVIEW

**Comment by mlenser** [comment]
Your version is from the April 28th version - you need to update before pushing.

**Comment by Rouby** [comment]
... is there an easy way of doing this? gitmerge seems to only produce shit

I dont know enough about all the changes you made to easily fix them by myself

**Comment by Rouby** [comment]
Wouldnt it be easier if you tried to merge them ? I have only replaced some of the texts with two span s.

**Comment by mlenser** [comment]
I'm pretty bad at merging - especially with github. I only know how to take exactly what GitHub gives me and then I'd have to modify it from there :S

**Comment by Rouby** [comment]
I think it would be best if you just copy/paste the translations I have done so far and insert them into your master-file.

You changed quit alot in basic designs (col-classes and such) that I cant guarantee to catch all if I try to merge them.

Let me know what you think.

**Comment by Rouby** [comment]
Maybe try a diff between the april 28th version and my commits, then you can easily get all the translations I think.

**Comment by mlenser** [comment]
If you know how I can do that with intellij then please let me know.

**Comment by Rouby** [comment]
I have created a patch file, you should be able to open it with a simple text editor and see the translations

https://drive.google.com/file/d/0B-6WMKNI8ugYTVVkbmVZUEY2T2c/view?usp=sharing

**Comment by mlenser** [comment]
I'm diffing from https://raw.githubusercontent.com/Rouby/roll20-character-sheets/master/D%26D_5e_Shaped/D%26D_5e.html

A lot of that is not in the patch file.

Working through it 1 by 1, it'll be slow.

**Comment by mlenser** [comment]
"Geschicklichkeit" is much too long. Is there an abbreviation that I can use?
"Umgang mit Tieren" is too long as well.

**Comment by Rouby** [comment]
Geschicklichkeit - Geschick.
Umgang mit Tieren - Tierumgang

Yeah I figured those might be too long ;)

**Comment by Rouby** [comment]
Thanks for taking the time to merge this :)

Maybe we can split the file into pieces (like the tabs each in different files) and "build"/cat them together? Would make working on them alot easier I think.

Or maybe use some "higher-level" to generate the HTML and even use translation-tables. But I dont know if that might be too much overhead.

I once used T4 text-templates in Visual Studio to generate something like this.

**Comment by mlenser** [comment]
I agree - I thought about splitting out all the pages to separate files and then concatenating them all when I push it live, but it's an extra step that contributors would have to figure out.

More that need to be shortened:
"Einschüchterung"
"Religions Wissen"
"Überlebenskunst"
"Reichweite" is 2 characters too big if it can be shortened at all.

**Comment by Rouby** [comment]
"Reichw."

Maybe use grunt / gulp? Its a very common and easy to use build-tool.

**Comment by mlenser** [comment]
Ya, I use grunt for work. I could setup grunt/gulp to do some concatenation - I've just been lazy about it.

I added a few more to the list above. Done with the core page once I put the shorter ones in.

**Comment by Rouby** [comment]
Einschücht.
Religion
Überleben

Maybe it would be better to make a little more room for the names? Some of the abbreviations may be harder to understand.

**Comment by mlenser** [comment]
It's only a problem on the Core page as that page is very limited in it's structure.

Can I just shorten the words and add ".."?
For example I can do "Religions Wiss.." which is maybe better than just "Religion".

**Comment by Rouby** [comment]
Yeah you can do that. If it does not work out I will think of some other shortings that may make more sense.

**Comment by mlenser** [comment]
You can always look it over and tell me any mistakes after.

I've committed Core and Background - you can see them now. I'll do the other pages shortly - taking a short break for now.

**Comment by mlenser** [comment]
Going to bed, will have to finish tomorrow or next week (I have my session on Sunday)

**Comment by mlenser** [comment]
Finished the Class page.

Make sure you update before you do any other pages please. :)

**Pull request closed without merging**
