### PR TITLE
small fixes for french

### PR DESCRIPTION
**Pull request by Alzam01**

### CODE REVIEW

**Comment by Alzam01** [comment]
up

**Comment by mlenser** [comment]
Why do you have the nbsp? Shouldn't be needed as English doesn't have it.

I'd prefer they be removed. Let me know and I can merge.

Though I won't be able to compile as I've left my house for vacation.

**Comment by Alzam01** [comment]
That was a dirty way to try and fix the fact that the traduction for sorceler was a little bit too long and displayed inside the warlock. It's removed now.

**Comment by Alzam01** [comment]
Enjoy your vacation :)

**Pull request merged**
