### PR TITLE
Proposed approach to handling MM import

### PR DESCRIPTION
**Pull request by symposion**
So this is what I'm proposing to deal with import from the MM. Hopefully fairly unintrusive. It seems to work ok, but as I mentioned there are occasional oddnesses with some toggles not being set quite properly. Perhaps because more stuff is being set all in one go at the beginning and it's triggering things in a slightly different order as a result?

Anyway let me know what you think - although I'm off to bed now so i won't respond this evening...

### CODE REVIEW

**Comment by mlenser** [comment]
I don't think requiring the sheet to close and then reopen is a good user experience. Picture a user importing spells. he'd have to import all the spells and then close and reopen the sheet. Or creating a new npc. You'd have to first create the npc and then attach an avatar and t hen close the sheet and then run the command and then open the sheet and then adjust the avatar.

Not would a button click really help this experience much.

This is inherently the problem - if API can't trigger sheetworkers then there is no way to do it automatically right away that I can think of.

I would highly recommend making a bug report and getting an official word from Roll20 because they can't expect sheets to handle this.

**Comment by symposion** [comment]
Ok, I will try, but as I pointed out in our conversation on Roll20, Riley has already publicly stated that the limitation is deliberate and has outlined a longer-term plan that involves running a copy of the sheet workers on the API server. I think it's extremely unlikely that the appearance of a bug report on an issue that has already been extensively discussed is going to suddenly make them drop what they're doing and change this.

I've invested quite a lot of time in the import script and I'd be... disappointed... to say the least... to see the functionality shelved for months while we wait for a change like this. I agree that the experience isn't ideal but it's better than nothing, which is the current alternative. The impact of the change on the sheet and the sheet-workers is minimal as well, so it's not like it's a huge maintenance issue to have this code in their while we wait for Roll20 to sort this out.

Also, the new NPC import experience is fine - which is one of the major use cases:
- Create token
- Paste in GM notes text
- select token
- run !shaped-import
- open the newly-created character

Which is exactly what I did with the old import anyway! Granted, spell import won't work nicely without a refresh button, and the experience for updating a character will be worse; but I think there are people out there who are waiting on the MM import functionality who would be pleased to have _something_ that works rather than us delivering nothing at all because it doesn't work quite the way we'd like it to.

**Comment by symposion** [comment]
For reference, here is the most useful discussion including Riley's response:
- https://app.roll20.net/forum/post/2872260/sheetworkers-how-to-react-to-roll-buttons-abilities-and-skills/?pageforid=2877195#post-2877195

More recently, I raised exactly this issue on the Pro forum and explicitly asked for a Roll20 response on the future plans - no response - 
- https://app.roll20.net/forum/post/3040799/future-plans-for-api-slash-sheet-workers/?pageforid=3040799#post-3040799

And another:
- https://app.roll20.net/forum/post/2766747/api-and-sheet-workers

I really don't think that we're going to get rapid movement on this one

**Comment by symposion** [comment]
As requested:
1. https://app.roll20.net/forum/post/3123549/api-changes-dont-trigger-sheet-workers/
2. https://app.roll20.net/forum/post/3123561/incorrect-change-events-firing-for-sheet-workers/

**Comment by mlenser** [comment]
This looks fine on second look. I shouldn't look at pull requests late at night. :P

As you say the process is the same as before:
- Create token
- Paste in GM notes text
- select token
- run !shaped-import
- open the newly-created character

We'll likely have to do some kind of button for spells - perhaps below the spells area.

**Pull request merged**
