### PR TITLE
various russian translation fixes and cleanups

### PR DESCRIPTION
**Pull request by Sadariz**
Overall mistakes and visual fixes

### CODE REVIEW

**Comment by mlenser** [comment]
The indentations need to be fixed. I can't fix them all again - I don't have the time. If you look at the diff in github you'll see that the russian translations don't line up.

**Comment by Sadariz** [comment]
OK, i try. It's strange, cos i don't see them in Notepad++, only in differences. I'll try another editor.

**Comment by Alzam01** [comment]
That's because you are using tabs instead of space I think. There is a option that let you "convert" all the tabs to spaces (look for "Blank Operations" in "Edit")

**Comment by mlenser** [comment]
I will merge this and fix any issues if you resolve the conflicts.

**Pull request closed without merging**
