### PR TITLE
Generate defaults for 5eShapedSpellbook Script

### PR DESCRIPTION
**Pull request by symposion**
Hi,

I mentioned a while back that I'd (a) like to have a more robust way of ensuring that people are using the right version of your character sheet with my evil spellbook script and (b) would like the unpleasant copy-paste-convert-to-json thing for the default values to be automated so that it is less tedious and error-prone. 

What I've done here is to edit you gulpfile.js to make it generate a file called spellDefaults.js. It builds this by extracting info from components/spells/spell-page.html and writing it out as JSON. It then takes a hash of the generated json and adds it as a property on a wrapper object. Finally, it injects this hash value as a hidden attribute on the character sheet.

This means that people can install spellDefaults.js whenever they update their character sheet. My script can check that the hash from the character sheet corresponds with the hash in the defaults javascript to ensure that compatible versions are being run.

I also took the liberty of checking in a package.json (and associated .gitignore) so that executing the gulpfile is easier for others checking out the repository.

I hope you don't feel that this is all too evil to include in your repository. Despite having spent a certain amount of time on this, I would be the first to see it all burn in coding hell once Roll20 provides a credible alternative. In the meantime it seemed like the least-bad solution to providing a way for people who have API access to do more with spells.

Cheers,

Lucian

### CODE REVIEW

**Comment by mlenser** [comment]
I'm on vacation for the weekend, but can take a closer look when I'm back.

Looks good overall but the json structure should match the one I use for my spell importer - see that github for it. If you match that it'll make it easier for both of us.

Thanks for adding package.json

**Comment by symposion** [comment]
Cool. WIth regards to the JSON format, I'm not sure I understand how that would work. The JSON format that I'm exporting from the sheet isn't really designed as a transmission format for spell information: it's designed to provide the script with defaults for the character sheet attributes themselves. This is especially important because many of the attributes that do end up being set explicitly (and are thus available to the API) contain references to other attributes (e.g. the hidden variables) which are not. The script needs to be able to lookup these references _as they are named in the sheet_, or this mechanism won't work. Many of these (like all the toggle vars) are not things that would belong in the JSON format that you use for importing spells anyway - they are specific to the mechanics of the character sheet itself.

To the extent that a mapping exists between your JSON format and the attributes that exist in the character sheet, it is contained in the code of your importSpell function. I guess we could document this mapping elsewhere in another JSON file, but this seems like a lot of extra work for not much benefit. It was really never my intention that this JSON format should ever be used for anything other than documenting what attributes existing in the character sheet, and exposing those defaults for them that are coded into the sheet, but which Roll20 hides from the API. I certainly wouldn't want it to end up being an alternative data store/import format for spells - that's something you've covered already with the sheet + your importer, and I have no desire to reinvent any of that!

Perhaps I'm misunderstanding what you mean, though, or I've just missed something very obvious about how this could be done in a nicer way. 

Anyway, we can continue all this next week perhaps. Enjoy your vacation!

**Comment by mlenser** [comment]
The problem is the data on the sheet is not organized well due to legacy names. Though I won't be a stickler here - as long as it's just used for it's current purpose and not for storing the values of individual spells.

I'm going to move some of the files around though.

**Comment by mlenser** [comment]
Actually I need you to update, build, and then commit (this pull request will be updated).

In the future it's best to not commit the compiled versions as I'll recreate them when I merge.

**Comment by symposion** [comment]
Hey Mark,

I've rebased my commit onto your latest, and removed the compiled versions from the commit in the process. Should now merge OK. Obviously I haven't rebuilt now since I've removed the compiled versions from the commit. I don't _think_ I've messed anything up in the process, but rebasing gets confusing sometimes!

As concerns the legacy names, one thing that may help put your mind at rest is that the idea of this system is precisely to _avoid_ any dependency between my script and your naming. I only reference a small number of the values (e.g. 'spellname') directly by name to handle some of the core logic - the rest are simply there to ensure that all the internal references between the various attributes resolve properly in the absence of the defaults via the API. To the extent that I _am_ referencing the attributes directly, I fully accept that I'm working with an undocumented private API and will need to keep track of changes myself to make sure things don't break. Hopefully repeating sections will get fixed soon enough that I never even have to worry about that!

Cheers,
Lucian

**Comment by mlenser** [comment]
Sorry that I've been so delayed with this.

**Comment by mlenser** [comment]
It seems to generate "undefined" though. Maybe it was me moving files around. If you could fix it that'd be great as I leave for vacation for a week soon.

**Comment by symposion** [comment]
Hey Mark,

I've just pulled your latest changes and I'm not quite sure what your intention was so I don't know what the best way of fixing it would be. The main problem seems to be that you've changed the src of the addSpellDataHash task to be precompiled/spellDefaults.json, but the gulpfile is already in "precompiled" so that resolves to precompiled/precompiled/spellDefaults.json, which doesn't exist.

I'm guessing that the intention is that both spellDefaults.json and spellDefaults.js should end up in the "precompiled" directory? If so, then I think changing the src for addSpellDataHash back to just "spellDefaults.json" should fix the problem. But I'm not 100% clear what you want do do, and I'm also a bit puzzled because although I don't get spellDefaults.js generated thanks to this issue, I don't get "undefined". Where is it giving you "undefined"? In the json? Do you have some changes that aren't pushed to github maybe?

Cheers,

**Comment by mlenser** [comment]
My intention is to have it all in precompiled, ya

I can edit it tomorrow if you don't.

Sorry, my brain is a little frazzled, but I didn't want to forget it again.

**Pull request merged**
